#!/usr/bin/env python3
"""把 Markdown 文档渲染成给人看的 HTML 视图。

定位（真相源约定，各 skill 引用此处，不复述）：
- .md 是唯一事实源，供 AI / 工具消费；.html 是派生视图，只给人审阅。
- .html 永不手工编辑、不进 git（见 .gitignore）；.md 变更后重跑本脚本再生成。
- 渲染是确定性的：模板固定，Markdown 原文嵌入页面，浏览器端渲染。
  marked 内联进 HTML（vendor `_shared/vendor/marked.min.js`，缺失退 CDN），正文离线可读；
  mermaid 走 CDN，加载失败降级为可折叠源码卡（不糊原文）。
  构建期把 `**…**` 预转 <strong>，绕开 CommonMark 与中文标点的强调定界冲突。
- 仅用于本仓库自产的可信文档；不做 HTML sanitize，不要拿它渲染外部内容。
- 样式按文档家族分层（都内嵌在本文件，无独立 CSS 文件——单文件 HTML 可携带、跨目录不断链）：
  · 基础层：暖纸色低饱和主题（护眼），全文档共用；目录 ≥1240px 常驻侧栏 + 阅读位置高亮
  · PRD 层：EARS 徽章、来源芯片、句式分组工具条（模式命中才生效）
  · Plan/Epic/Story 层：文档头横幅（类型/epic/policy/status 芯片）、
    D-ID/ACD/T/U/Story 令牌芯片、决策状态与 Confidence 芯片、表格斑马纹；
    三区制分层（"合同区"h2 命中才生效）：合同区容器+角标、合同块语义色卡片、
    Must Hold 不变量卡、"N、导语。正文"概念段升格为编号卡片；
    用户旅程升格（表头签名"步骤/场景+页面+用户行为+系统响应+覆盖"命中才生效）：
    主旅程表→双泳道旅程板（用户/系统泳道×步骤列，SVG 连线画主路径）、
    异常表→场景卡片组，原表格在 HTML 里不再展示（.md 仍是数据源）；
    同目录存在 archify 手工旅程图（journey.html）时主旅程改为 iframe 引用它，
    过期兜底：journey.source-digest 记录生成时的旅程章节摘要，构建时比对，
    不一致 → 页面警示横幅 + stderr warning（更新流程见 journey_embed docstring）
  · Task packet 层（按文件名判族：T{NNN}-*.md / task-index.md，无需 frontmatter）：
    头部元数据行（Epic/Unit/Depends/Wave + Execution note 的 Risk/UI class/Test policy）
    升格 banner 芯片；Generated from 折叠为溯源卡；Task scope 升格警示 callout；
    Read first / Write scope / Execution note / Stop conditions / DoD 复用合同块语义卡片
  按 frontmatter `type:`、内容特征与文件名自动判族，非对应文档零影响。

用法：
    python3 .agents/skills/_shared/scripts/render_doc_html.py <file.md | dir> [...]

输入是目录时递归处理其下所有 *.md；输出为同目录同名 .html，直接覆盖。
单个文件渲染失败不中断批量，最后以非零 exit code 汇总报告。
"""

import hashlib
import html
import json
import re
import string
import sys
from pathlib import Path

MERMAID_SCRIPT_TAG = (
    '<script defer src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>'
)
MARKED_CDN_TAG = '<script defer src="https://cdn.jsdelivr.net/npm/marked@14/marked.min.js"></script>'
# marked 优先内联（离线可用、消灭"CDN 失败整页糊 Markdown 原文"）；vendor 缺失时退回 CDN
VENDOR_MARKED = Path(__file__).resolve().parent.parent / "vendor" / "marked.min.js"

_STRONG_RE = re.compile(r"\*\*([^*\n]+?)\*\*")
_FENCE_RE = re.compile(r"^\s{0,3}(```|~~~)")


def fix_cjk_strong(body: str) -> str:
    """构建期把 **…** 预转 <strong>。

    CommonMark 的强调定界规则与中文标点冲突（如 `**…。**` 后接汉字时闭合失效），
    浏览器端 marked 会露出字面星号或加粗渗漏到后文；在 Python 侧确定性转换绕开该坑。
    跳过 code fence 与行内 code span（按反引号奇偶段判断）。
    """
    out_lines = []
    in_fence = False
    for line in body.split("\n"):
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            out_lines.append(line)
            continue
        if in_fence or "**" not in line:
            out_lines.append(line)
            continue
        parts = line.split("`")
        for i in range(0, len(parts), 2):
            parts[i] = _STRONG_RE.sub(r"<strong>\1</strong>", parts[i])
        out_lines.append("`".join(parts))
    return "\n".join(out_lines)


def marked_script_tag() -> str:
    if VENDOR_MARKED.is_file():
        js = VENDOR_MARKED.read_text(encoding="utf-8").replace("</script", "<\\/script")
        return "<script>" + js + "</script>"
    return MARKED_CDN_TAG

PAGE_TEMPLATE = string.Template(r"""<!DOCTYPE html>
<!-- GENERATED by .agents/skills/_shared/scripts/render_doc_html.py from $source_name — DO NOT EDIT. Markdown 为唯一事实源。 -->
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<style>
:root {
  color-scheme: light dark;
  --bg: #f6f2e8;
  --surface: #fffdf6;
  --surface-2: #fbf8ef;
  --text: #3a352b;
  --muted: #7c7466;
  --border: #e4dcc9;
  --border-soft: #ede7d7;
  --link: #7a5c2e;
  --code-bg: #efe9da;
  --accent: #6d5a35;
  --good: #5c7345;
  --good-bg: #e9edda;
  --warn: #96602a;
  --warn-bg: #f6e7d4;
  --bad: #9a4b32;
  --bad-bg: #f2ded4;
  --info: #48687a;
  --info-bg: #e3ecf1;
  --shadow: 0 1px 3px rgba(90, 78, 54, 0.08), 0 4px 18px rgba(90, 78, 54, 0.06);
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #26221a;
    --surface: #2e2921;
    --surface-2: #332d24;
    --text: #d9d2c2;
    --muted: #9a917e;
    --border: #463f30;
    --border-soft: #3b3528;
    --link: #c9a35f;
    --code-bg: #383226;
    --accent: #c9a35f;
    --good: #b9c48b; --good-bg: #3a4028;
    --warn: #d8b083; --warn-bg: #4a3a26;
    --bad: #d99a74;  --bad-bg: #472f22;
    --info: #a9c3d2; --info-bg: #32424c;
    --shadow: 0 1px 3px rgba(0,0,0,0.3), 0 4px 18px rgba(0,0,0,0.22);
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 15.5px/1.8 "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei",
    -apple-system, "Segoe UI", sans-serif;
}
main { max-width: 60rem; margin: 0 auto; padding: 2.2rem 1.6rem 4rem; }
h1, h2, h3, h4 { line-height: 1.4; margin: 2.1em 0 0.6em; letter-spacing: 0.01em; }
h1 {
  font-family: "Songti SC", "Noto Serif SC", "Source Han Serif SC", Georgia, serif;
  font-size: 1.9rem; font-weight: 700; margin-top: 0.4em;
  border: none; padding-bottom: 0;
}
h2 {
  font-family: "Songti SC", "Noto Serif SC", "Source Han Serif SC", Georgia, serif;
  font-size: 1.32rem; font-weight: 700;
  padding: 0.25em 0 0.35em; border-bottom: 1px solid var(--border);
}
h3 { font-size: 1.08rem; }
a { color: var(--link); text-underline-offset: 0.2em; }
p, ul, ol { margin: 0.7em 0; }
li { margin: 0.3em 0; }
li > input[type="checkbox"] { margin-right: 0.5em; accent-color: var(--accent); }
strong { color: color-mix(in srgb, var(--text) 88%, var(--accent)); }
code {
  background: var(--code-bg);
  border-radius: 5px;
  padding: 0.12em 0.4em;
  font: 0.86em/1.6 "SF Mono", Menlo, Consolas, monospace;
}
pre {
  background: var(--code-bg);
  border: 1px solid var(--border-soft);
  border-radius: 10px;
  padding: 0.9rem 1.1rem;
  overflow-x: auto;
  box-shadow: var(--shadow);
}
pre code { background: none; padding: 0; }
/* —— 表格：卡片化 + 斑马纹 + 行分隔线（弃全格线）；JS 包 .table-wrap 撑满宽 + 超宽滚动 —— */
.table-wrap {
  overflow-x: auto;
  margin: 1.1em 0;
  border: 1px solid var(--border);
  border-radius: 10px;
  background: var(--surface);
  box-shadow: var(--shadow);
}
table {
  width: 100%;
  border-collapse: collapse;
  margin: 0;
  background: var(--surface);
}
th, td {
  border: none;
  border-bottom: 1px solid var(--border-soft);
  padding: 0.55em 0.9em;
  text-align: left;
  vertical-align: top;
}
/* 末列通常是"说明/结果"类长文，给最小宽度防止被代码列挤成竖条 */
tr > td:last-child:not(:first-child), tr > th:last-child:not(:first-child) { min-width: 15em; }
td + td, th + th { border-left: 1px solid var(--border-soft); }
tbody tr:nth-child(even) { background: var(--surface-2); }
tbody tr:last-child td { border-bottom: none; }
th {
  background: color-mix(in srgb, var(--code-bg) 75%, var(--surface));
  white-space: nowrap;
  font-size: 0.86em;
  letter-spacing: 0.05em;
  color: var(--muted);
  text-transform: uppercase;
}
blockquote {
  margin: 1em 0;
  padding: 0.55em 1.1em;
  border-left: 3px solid var(--accent);
  color: var(--muted);
  background: var(--surface);
  border-radius: 0 10px 10px 0;
}
hr { border: none; border-top: 1px solid var(--border); margin: 2.5em 0; }
.mermaid {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 1rem;
  margin: 1em 0;
  text-align: center;
  box-shadow: var(--shadow);
}
details.frontmatter {
  background: var(--surface);
  border: 1px solid var(--border-soft);
  border-radius: 10px;
  padding: 0.45rem 1rem;
  margin: 1.2rem 0 0;
  color: var(--muted);
  font-size: 0.88rem;
}
details.frontmatter pre { border: none; background: none; padding: 0.3rem 0; box-shadow: none; }
footer {
  margin-top: 3.5rem; padding-top: 1rem;
  border-top: 1px solid var(--border);
  color: var(--muted); font-size: 0.85rem;
}
.load-error {
  border: 1px solid var(--border);
  background: var(--surface);
  border-radius: 10px;
  padding: 0.8rem 1rem;
  color: var(--muted);
}
/* —— 通用芯片 —— */
.chip {
  display: inline-block;
  font-size: 0.8em;
  line-height: 1.55;
  padding: 0.04em 0.6em;
  border-radius: 999px;
  white-space: nowrap;
  vertical-align: 0.06em;
  font-family: "SF Mono", Menlo, Consolas, monospace;
}
/* —— 文档头横幅（plan/epic/story 族） —— */
header.doc-banner {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.1rem 1.4rem;
  margin-bottom: 1.6rem;
  box-shadow: var(--shadow);
}
header.doc-banner .kicker {
  font-size: 0.78rem; letter-spacing: 0.22em; text-transform: uppercase;
  color: var(--accent); margin-bottom: 0.3rem;
}
header.doc-banner .meta-row {
  display: flex; flex-wrap: wrap; gap: 0.45rem;
  margin-top: 0.55rem; font-size: 0.95rem;
}
.chip.meta { background: var(--code-bg); color: var(--muted); }
.chip.pol-strict { background: var(--bad-bg); color: var(--bad); font-weight: 600; }
.chip.pol-fast { background: var(--good-bg); color: var(--good); font-weight: 600; }
.chip.doc-status { background: var(--info-bg); color: var(--info); }
/* —— ID 令牌芯片 —— */
.tok { font-weight: 600; }
.tok-d    { background: var(--info-bg); color: var(--info); }
.tok-acd  { background: var(--bad-bg); color: var(--bad); }
.tok-t    { background: var(--good-bg); color: var(--good); }
.tok-u    { background: #ece6f0; color: #6d5b7e; }
.tok-story{ background: var(--warn-bg); color: var(--warn); }
@media (prefers-color-scheme: dark) { .tok-u { background: #3d3545; color: #beadd0; } }
/* —— 状态 / Confidence 芯片 —— */
.st-assumed  { background: var(--warn-bg); color: var(--warn); }
.st-pending  { background: var(--bad-bg); color: var(--bad); }
.st-approved { background: var(--good-bg); color: var(--good); }
.st-synced   { background: var(--good-bg); color: var(--good); }
.conf-H { background: var(--good-bg); color: var(--good); }
.conf-M { background: var(--warn-bg); color: var(--warn); }
.conf-L { background: var(--bad-bg); color: var(--bad); }
/* —— EARS 增强（PRD 族，模式命中才生效） —— */
#content li.req {
  list-style: none;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0.55em 0.9em;
  margin: 0.6em 0;
  box-shadow: var(--shadow);
}
.ears-badge {
  display: inline-block; font-size: 0.78em; line-height: 1.5;
  padding: 0.05em 0.55em; border-radius: 999px;
  margin: 0 0.45em 0 0.35em; vertical-align: 0.08em; white-space: nowrap;
}
.ears-when     { background: #e3ecf1; color: #48687a; }
.ears-if       { background: #f6e7d4; color: #96602a; }
.ears-while    { background: #e9edda; color: #63713d; }
.ears-where    { background: #ece6f0; color: #6d5b7e; }
.ears-ubi      { background: #e8e4da; color: #6b6355; }
.ears-scenario { background: #dfeeea; color: #3f6f63; }
code.src-chip { font-size: 0.78em; border-radius: 999px; padding: 0.05em 0.6em; white-space: nowrap; }
.subj { font-weight: 600; color: var(--link); }
code.src-user       { background: #e4ead8; color: #5c6b3c; }
code.src-research   { background: #dfe9ee; color: #4b7086; }
code.src-inferred   { background: #f7efdf; color: #8a6a34; border: 1px dashed #c2a26a; }
code.src-assumption { background: #f2dfd6; color: #9a5636; border: 1px dashed #bd7d55; }
#content h3.epic-head { border-left: 4px solid var(--link); padding-left: 0.6em; }
.src-toolbar {
  display: flex; flex-wrap: wrap; gap: 0.5rem 0.9rem; align-items: center;
  font-size: 0.85rem; color: var(--muted);
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0.5rem 0.9rem;
  margin: 1rem 0 1.4rem;
}
.src-toolbar button {
  font: inherit; font-size: 0.95em; color: var(--link);
  background: none; border: 1px solid var(--border); border-radius: 999px;
  padding: 0.1em 0.8em; cursor: pointer;
}
body.filter-inferred .src-toolbar button { background: var(--code-bg); }
body.filter-inferred #content li.req:not(.has-inferred) { display: none; }
details.toc {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0.6rem 1rem;
  margin-bottom: 1.5rem;
  font-size: 0.9rem;
  box-shadow: var(--shadow);
}
details.toc summary { cursor: pointer; font-weight: 600; }
details.toc ul { margin: 0.3em 0; padding-left: 0.2em; list-style: none; }
details.toc li { margin: 0.28em 0; }
details.toc a { text-decoration: none; color: var(--muted); }
details.toc a:hover { color: var(--link); }
details.toc a.active { color: var(--accent); font-weight: 600; }
details.toc li.toc-divider {
  margin: 0.7em 0 0.35em; padding-top: 0.6em;
  border-top: 1px solid var(--border-soft);
  font-size: 0.78em; letter-spacing: 0.18em; color: var(--accent); font-weight: 600;
}
@media (min-width: 1240px) {
  details.toc {
    position: fixed; top: 2rem; left: 1.2rem; width: 240px;
    max-height: calc(100vh - 4rem); overflow: auto; margin-bottom: 0;
  }
  details.toc summary { display: none; }
  main { margin-left: max(280px, calc((100vw - 60rem) / 2)); margin-right: auto; }
}
/* —— 三区制分层：合同区容器 / 合同块卡片 / 附录弱化 —— */
#content > hr:has(+ section.zone-contract) { display: none; }
section.zone-contract {
  position: relative;
  background: color-mix(in srgb, var(--surface-2) 72%, var(--bg));
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 0.4rem 1.4rem 1.3rem;
  margin: 3rem 0 2.2rem;
  box-shadow: var(--shadow);
}
section.zone-contract::before {
  content: "合同区 · CONTRACTS";
  position: absolute; top: -0.85em; left: 1.1rem;
  background: var(--accent); color: var(--bg);
  font-size: 0.72rem; font-weight: 600; letter-spacing: 0.18em;
  padding: 0.18em 0.95em; border-radius: 999px;
}
section.zone-contract > h2 { border-bottom: none; margin: 0.9em 0 0.2em; font-size: 1.18rem; }
section.zone-contract > hr { display: none; }
section.zone-contract > blockquote { font-size: 0.88em; margin: 0.6em 0 1em; }
.contract-block {
  --blk: var(--accent);
  background: var(--surface);
  border: 1px solid var(--border);
  border-left: 4px solid var(--blk);
  border-radius: 10px;
  padding: 0.75rem 1.15rem 0.9rem;
  margin: 1rem 0;
  box-shadow: var(--shadow);
}
.contract-block > hr:last-child { display: none; }
.contract-block > h3 {
  display: flex; align-items: center; gap: 0.55em;
  margin: 0.1em 0 0.55em; font-size: 1.02rem;
}
.contract-block > h3::before {
  content: ""; width: 0.6em; height: 0.6em; border-radius: 50%;
  background: var(--blk); flex: none;
}
.blk-terms { --blk: var(--accent); }
.blk-api   { --blk: var(--info); }
.blk-data  { --blk: var(--good); }
.blk-ui    { --blk: var(--warn); }
.blk-must, .blk-risk { --blk: var(--bad); }
.blk-check { --blk: var(--info); }
.blk-must ul { list-style: none; padding-left: 0; }
.blk-must li.invariant {
  background: color-mix(in srgb, var(--bad-bg) 42%, var(--surface));
  border-left: 3px solid var(--bad);
  border-radius: 8px;
  padding: 0.45em 0.9em 0.45em 2.1em;
  margin: 0.5em 0;
  position: relative;
}
.blk-must li.invariant::before {
  content: "⛨"; position: absolute; left: 0.7em; top: 0.42em; color: var(--bad);
}
section.zone-appendix h2, section.zone-appendix h3 { color: var(--muted); }
section.zone-appendix { color: color-mix(in srgb, var(--text) 82%, var(--muted)); }
/* —— 概念卡片（"N、导语。正文"段落自动升格，模式命中才生效） —— */
.concept-card {
  display: grid;
  grid-template-columns: 2rem 1fr;
  gap: 0.15rem 0.85rem;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 0.95rem 1.25rem;
  margin: 1.15rem 0;
  box-shadow: var(--shadow);
}
.concept-num {
  grid-row: span 2;
  width: 2rem; height: 2rem; border-radius: 50%;
  background: var(--accent); color: var(--bg);
  display: flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 0.95rem;
  margin-top: 0.15rem;
}
.concept-title { font-weight: 700; font-size: 1.03rem; align-self: center; }
.concept-body { grid-column: 2; }
/* 叙事段首加粗导语 → 阅读落点 */
#content > p > strong:first-child { color: var(--accent); }
/* 导读行卡：每节"只需记住的一句话"（"> 一句话：…" 引用块升格） */
blockquote.takeaway {
  background: color-mix(in srgb, var(--info-bg) 55%, var(--surface));
  border-left: 3px solid var(--info);
  color: var(--text);
  border-radius: 0 10px 10px 0;
  padding: 0.7em 1.1em;
}
blockquote.takeaway p { margin: 0; }
.takeaway-label {
  display: inline-block;
  font-size: 0.72em; font-weight: 600; letter-spacing: 0.18em;
  background: var(--info); color: var(--bg);
  border-radius: 999px; padding: 0.12em 0.75em;
  margin-right: 0.7em; vertical-align: 0.12em;
}
/* —— 用户旅程升格（Epic 族，表头签名命中才生效）：主旅程双泳道旅程板 + 异常场景卡 —— */
.jmap {
  margin: 1.15em 0;
  overflow-x: auto;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  box-shadow: var(--shadow);
  padding: 1.15rem 1.25rem 1.3rem;
}
.jmap-canvas {
  position: relative;
  min-width: fit-content;
  padding: 0.4rem 0.35rem;
  background-image:
    linear-gradient(color-mix(in srgb, var(--border-soft) 55%, transparent) 1px, transparent 1px),
    linear-gradient(90deg, color-mix(in srgb, var(--border-soft) 55%, transparent) 1px, transparent 1px);
  background-size: 42px 42px;
}
.jmap-links {
  position: absolute; inset: 0;
  width: 100%; height: 100%;
  pointer-events: none;
}
.jmap-links path.jmap-line { fill: none; stroke-width: 2.25; stroke-linejoin: round; }
.jmap-links .jmap-step-line { stroke: var(--info); }
.jmap-links .jmap-flow-line { stroke: var(--accent); }
.jmap-links .jmap-step-head { fill: var(--info); }
.jmap-links .jmap-flow-head { fill: var(--accent); }
.jmap-grid {
  position: relative;
  display: grid;
  grid-template-columns: repeat(var(--jmap-steps), minmax(12.5rem, 1fr));
  gap: 2.1rem 1.3rem;
  align-items: stretch;
}
.jmap-laneframe {
  position: relative;
  grid-column: 1 / -1;
  margin: -0.65rem -0.55rem;
  border: 1.5px dashed color-mix(in srgb, var(--border) 72%, var(--muted));
  border-radius: 14px;
  pointer-events: none; /* 定位元素叠在节点上方，放行文字选中与点击 */
}
.jmap-laneframe::before {
  content: attr(data-label);
  position: absolute; top: -0.8em; left: 0.95rem;
  background: var(--surface);
  padding: 0 0.65em;
  font: 600 0.72rem/1.6 "SF Mono", Menlo, Consolas, monospace;
  letter-spacing: 0.16em;
  color: var(--muted);
}
.jmap-frame-user::before { color: var(--good); }
.jmap-frame-sys::before { color: var(--info); }
.jmap-stephead {
  display: flex; align-items: center; flex-wrap: wrap;
  gap: 0.4em 0.55em;
  min-width: 0;
}
.jmap-stephead .journey-page {
  font-family: "SF Mono", Menlo, Consolas, monospace;
  font-size: 0.78em;
}
.jmap-stepnum {
  width: 1.7rem; height: 1.7rem; border-radius: 50%;
  background: var(--accent); color: var(--bg);
  display: flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 0.88rem; flex: none;
}
.jmap-node {
  border-radius: 12px;
  padding: 0.65rem 0.95rem 0.7rem;
  box-shadow: var(--shadow);
  font-size: 0.92em;
  line-height: 1.7;
  min-width: 0;
}
.jmap-user {
  background: color-mix(in srgb, var(--good-bg) 52%, var(--surface));
  border: 1.5px solid color-mix(in srgb, var(--good) 45%, var(--border));
}
.jmap-sys {
  background: color-mix(in srgb, var(--info-bg) 46%, var(--surface));
  border: 1.5px solid color-mix(in srgb, var(--info) 40%, var(--border));
}
.jmap-cover {
  margin-top: 0.5em; padding-top: 0.5em;
  border-top: 1px dashed color-mix(in srgb, var(--border) 65%, transparent);
  font-size: 0.88em; color: var(--muted);
}
/* archify 旅程图引用（journey.html 存在时替代泳道板） */
.jmap-ref { margin: 1.15em 0; }
.jmap-stale {
  background: color-mix(in srgb, var(--warn-bg) 60%, var(--surface));
  border-left: 3px solid var(--warn);
  color: var(--warn);
  border-radius: 0 10px 10px 0;
  padding: 0.55em 1em;
  margin-bottom: 0.7em;
  font-size: 0.9em;
}
.jmap-embed {
  display: block;
  width: 100%;
  height: 58rem;
  border: 1px solid var(--border);
  border-radius: 10px;
  background: var(--surface);
}
.jmap-detail { margin-top: 0.7em; }
.jmap-detail > summary {
  cursor: pointer;
  color: var(--muted);
  font-size: 0.9em;
}
.jmap-detail > .jmap { margin-top: 0.7em; }
.journey-page {
  font-size: 0.84em;
  color: var(--muted);
  background: var(--surface-2);
  border: 1px solid var(--border-soft);
  border-radius: 999px;
  padding: 0.05em 0.75em;
}
.journey-lane { display: flex; gap: 0.65em; align-items: baseline; margin: 0.3em 0; }
.lane-tag {
  flex: none;
  font-size: 0.72rem; font-weight: 600; letter-spacing: 0.14em;
  border-radius: 999px; padding: 0.12em 0.7em;
}
.lane-user > .lane-tag { background: var(--good-bg); color: var(--good); }
.lane-sys > .lane-tag { background: var(--info-bg); color: var(--info); }
.exception-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(min(21rem, 100%), 1fr));
  gap: 0.9rem;
  margin: 1.15em 0;
}
.exception-card {
  display: flex; flex-direction: column;
  background: var(--surface);
  border: 1px solid var(--border);
  border-left: 3px solid var(--warn);
  border-radius: 12px;
  padding: 0.7rem 1rem 0.75rem;
  box-shadow: var(--shadow);
}
.exception-title { font-weight: 600; margin-bottom: 0.45em; }
.exception-foot {
  display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between;
  gap: 0.35em 0.8em;
  margin-top: auto; padding-top: 0.55em;
  border-top: 1px dashed var(--border-soft);
  font-size: 0.92em;
}
.exception-cover { color: var(--muted); }
/* —— Task packet 族（按文件名判族命中才生效） —— */
header.doc-banner .scope-line { color: var(--muted); font-size: 0.92rem; margin-top: 0.35rem; }
#content p.task-meta-row { color: var(--muted); font-size: 0.86em; }
#content p.task-meta-row strong { color: var(--muted); }
details.gen-from {
  background: var(--surface);
  border: 1px dashed var(--border);
  border-radius: 10px;
  padding: 0.45rem 1rem;
  margin: 0.9rem 0;
  color: var(--muted);
  font-size: 0.88rem;
}
details.gen-from summary { cursor: pointer; }
details.gen-from p { margin: 0.4rem 0 0.1rem; }
.task-scope-callout {
  background: color-mix(in srgb, var(--warn-bg) 45%, var(--surface));
  border-left: 3px solid var(--warn);
  border-radius: 0 10px 10px 0;
  padding: 0.65em 1.1em;
  margin: 0.9em 0;
  font-size: 0.94em;
}
/* mermaid 加载失败降级卡 */
.mermaid-fallback {
  border: 1px dashed var(--border);
  background: var(--surface);
  border-radius: 10px;
  padding: 0.8rem 1.1rem;
  margin: 1em 0;
  color: var(--muted);
  font-size: 0.92em;
}
.mermaid-fallback pre { margin: 0.6em 0 0; box-shadow: none; }
.mermaid-fallback summary { cursor: pointer; }
@media (prefers-color-scheme: dark) {
  .ears-when     { background: #32424c; color: #a9c3d2; }
  .ears-if       { background: #4a3a26; color: #d8b083; }
  .ears-while    { background: #3a4028; color: #b9c48b; }
  .ears-where    { background: #3d3545; color: #beadd0; }
  .ears-ubi      { background: #3b372e; color: #b3aa99; }
  .ears-scenario { background: #2d413c; color: #97c2b5; }
  code.src-user       { background: #39402a; color: #b4c48a; }
  code.src-research   { background: #2f3f48; color: #9dc0d3; }
  code.src-inferred   { background: #453a24; color: #d3b578; border-color: #8a744b; }
  code.src-assumption { background: #472f22; color: #d99a74; border-color: #96674a; }
}
</style>
$marked_script_tag
$mermaid_script_tag
</head>
<body>
<main>
$banner_block
<div id="content"><p class="load-error">正在渲染…（若长时间停留此页，说明 CDN 渲染库未能加载，请直接阅读 <code>$source_name</code>）</p></div>
$frontmatter_block
<footer>由 <code>render_doc_html.py</code> 生成自 <code>$source_name</code> — Markdown 为唯一事实源，本 HTML 是派生视图，请勿手工编辑。</footer>
</main>
<script>
const MD_SOURCE = $md_json;
const DOC_META = $doc_meta_json;
const JOURNEY_EMBED = $journey_embed_json;
document.addEventListener("DOMContentLoaded", async () => {
  const contentEl = document.getElementById("content");
  if (typeof marked === "undefined") {
    contentEl.innerHTML = '<p class="load-error">渲染库加载失败（需要网络访问 CDN）。以下为 Markdown 原文：</p>';
    const pre = document.createElement("pre");
    pre.textContent = MD_SOURCE;
    contentEl.appendChild(pre);
    return;
  }
  contentEl.innerHTML = marked.parse(MD_SOURCE, { gfm: true });
  for (const code of contentEl.querySelectorAll("pre > code.language-mermaid")) {
    const div = document.createElement("div");
    div.className = "mermaid";
    div.textContent = code.textContent;
    code.parentElement.replaceWith(div);
  }
  // —— 用户旅程升格（Epic 族，表头签名命中才生效）：主旅程表→双泳道旅程板，异常表→场景卡 ——
  // 数据源仍是 .md 里的表格（AI/校验消费）；这里只换人读视图，签名不命中的表格原样保留。
  const SVGNS = "http://www.w3.org/2000/svg";
  const journeyLane = (cell, kind, tag) => {
    const lane = document.createElement("div");
    lane.className = "journey-lane lane-" + kind;
    const tagEl = document.createElement("span");
    tagEl.className = "lane-tag";
    tagEl.textContent = tag;
    const text = document.createElement("span");
    text.className = "lane-text";
    if (cell) text.append(...cell.childNodes);
    lane.append(tagEl, text);
    return lane;
  };
  const journeyPage = (cell) => {
    const s = document.createElement("span");
    s.className = "journey-page";
    if (cell) s.append(...cell.childNodes);
    return s;
  };
  const journeyCell = (cls, cell) => {
    const d = document.createElement("div");
    d.className = cls;
    if (cell) d.append(...cell.childNodes);
    return d;
  };
  // 主旅程 → 双泳道旅程板：用户/系统两条泳道、步骤为列；连线用 SVG overlay 画
  // 用户→系统（竖直）与 系统→下一步用户（直角肘线），ResizeObserver 随布局重绘。
  const buildJourneyMap = (rows, col) => {
    const jmap = document.createElement("div");
    jmap.className = "jmap";
    const canvas = document.createElement("div");
    canvas.className = "jmap-canvas";
    const svg = document.createElementNS(SVGNS, "svg");
    svg.setAttribute("class", "jmap-links");
    const grid = document.createElement("div");
    grid.className = "jmap-grid";
    grid.style.setProperty("--jmap-steps", rows.length);
    const place = (el, row, colIdx) => {
      el.style.gridRow = String(row);
      if (colIdx != null) el.style.gridColumn = String(colIdx);
      grid.append(el);
      return el;
    };
    const laneFrame = (row, cls, label) => {
      const d = document.createElement("div");
      d.className = "jmap-laneframe " + cls;
      d.dataset.label = label;
      return place(d, row);
    };
    laneFrame(2, "jmap-frame-user", "01 · 用户");
    laneFrame(3, "jmap-frame-sys", "02 · 系统");
    rows.forEach((cells, i) => {
      const head = document.createElement("div");
      head.className = "jmap-stephead";
      const num = document.createElement("span");
      num.className = "jmap-stepnum";
      num.textContent = cells[0] ? cells[0].textContent.trim() : "";
      head.append(num, journeyPage(cells[col.page]));
      place(head, 1, i + 1);
    });
    const userNodes = rows.map((cells, i) =>
      place(journeyCell("jmap-node jmap-user", cells[col.user]), 2, i + 1));
    const sysNodes = rows.map((cells, i) => {
      const d = journeyCell("jmap-node jmap-sys", cells[col.sys]);
      d.append(journeyCell("jmap-cover", cells[col.cover]));
      return place(d, 3, i + 1);
    });
    canvas.append(svg, grid);
    jmap.append(canvas);
    const path = (d, cls) => {
      const p = document.createElementNS(SVGNS, "path");
      p.setAttribute("d", d);
      p.setAttribute("class", cls);
      svg.append(p);
    };
    const draw = () => {
      const base = canvas.getBoundingClientRect();
      if (!base.width) return;
      svg.replaceChildren();
      const rel = (el) => {
        const r = el.getBoundingClientRect();
        return { left: r.left - base.left, right: r.right - base.left,
                 top: r.top - base.top, bottom: r.bottom - base.top,
                 cx: r.left - base.left + r.width / 2, cy: r.top - base.top + r.height / 2 };
      };
      userNodes.forEach((u, i) => {
        const ur = rel(u), sr = rel(sysNodes[i]);
        path("M " + ur.cx + " " + ur.bottom + " L " + ur.cx + " " + (sr.top - 5),
          "jmap-line jmap-step-line");
        path("M " + (ur.cx - 4.5) + " " + (sr.top - 6) + " L " + (ur.cx + 4.5) + " " +
          (sr.top - 6) + " L " + ur.cx + " " + sr.top + " Z", "jmap-step-head");
        if (i + 1 < userNodes.length) {
          const nu = rel(userNodes[i + 1]);
          const gx = (sr.right + nu.left) / 2;
          path("M " + sr.right + " " + sr.cy + " L " + gx + " " + sr.cy + " L " + gx + " " +
            nu.cy + " L " + (nu.left - 5) + " " + nu.cy, "jmap-line jmap-flow-line");
          path("M " + (nu.left - 6) + " " + (nu.cy - 4.5) + " L " + (nu.left - 6) + " " +
            (nu.cy + 4.5) + " L " + nu.left + " " + nu.cy + " Z", "jmap-flow-head");
        }
      });
    };
    const ro = new ResizeObserver(draw);
    ro.observe(grid);
    // 挂到元素上防 GC：无强引用的 ResizeObserver 可能被回收，
    // 导致延迟显示的板子（如闭合 details 内）展开时永远画不出连线
    jmap.__ro = ro;
    jmap.__redraw = draw;
    return jmap;
  };
  for (const tbl of [...contentEl.querySelectorAll("table")]) {
    const heads = [...tbl.querySelectorAll("thead th")].map((th) => th.textContent.trim());
    const isMain = heads[0] === "步骤";
    const isBranch = heads[0] === "场景";
    const col = {
      page: heads.findIndex((h) => h.includes("页面")),
      user: heads.findIndex((h) => h.includes("用户行为")),
      sys: heads.findIndex((h) => h.includes("系统响应")),
      cover: heads.findIndex((h) => h.includes("覆盖")),
    };
    if ((!isMain && !isBranch) || Object.values(col).some((i) => i < 0)) continue;
    const rows = [...tbl.querySelectorAll("tbody tr")].map((tr) => [...tr.children]);
    if (!rows.length) continue;
    // 同目录有 archify 手工旅程图 → 主旅程 iframe 引用它（过期时加警示）；没有则回落泳道板
    if (isMain && JOURNEY_EMBED) {
      const wrap = document.createElement("div");
      wrap.className = "jmap-ref";
      if (JOURNEY_EMBED.stale) {
        const warn = document.createElement("div");
        warn.className = "jmap-stale";
        warn.textContent = "⚠ 此图为 archify 手工生成，源摘要与当前旅程章节不一致，可能已过期" +
          "——请基于 journey.workflow.json 重新生成；存疑时以 epic.md 表格为准。";
        wrap.append(warn);
      }
      const frame = document.createElement("iframe");
      frame.className = "jmap-embed";
      frame.src = JOURNEY_EMBED.src;
      frame.loading = "lazy";
      frame.title = "主旅程图（archify）";
      wrap.append(frame);
      // archify 图是有损压缩视图（节点只放短语）；全文细节收进折叠的泳道板，按需展开
      const det = document.createElement("details");
      det.className = "jmap-detail";
      const sum = document.createElement("summary");
      sum.textContent = "完整步骤明细（含未删节的用户行为/系统响应）";
      const board = buildJourneyMap(rows, col);
      det.append(sum, board);
      det.addEventListener("toggle", () => {
        if (det.open) requestAnimationFrame(board.__redraw);
      });
      wrap.append(det);
      tbl.replaceWith(wrap);
      continue;
    }
    let box;
    if (isMain) {
      box = buildJourneyMap(rows, col);
    } else {
      box = document.createElement("div");
      box.className = "exception-grid";
      for (const cells of rows) {
        const cover = document.createElement("span");
        cover.className = "exception-cover";
        if (cells[col.cover]) cover.append(...cells[col.cover].childNodes);
        const card = document.createElement("div");
        card.className = "exception-card";
        const title = document.createElement("div");
        title.className = "exception-title";
        if (cells[0]) title.append(...cells[0].childNodes);
        const foot = document.createElement("div");
        foot.className = "exception-foot";
        foot.append(journeyPage(cells[col.page]), cover);
        card.append(title, journeyLane(cells[col.user], "user", "用户"),
          journeyLane(cells[col.sys], "sys", "系统"), foot);
        box.append(card);
      }
    }
    tbl.replaceWith(box);
  }
  // —— 表格包一层 .table-wrap：撑满容器宽（列不再挤成窄条），超宽时容器内横向滚动 ——
  for (const t of contentEl.querySelectorAll("table")) {
    const w = document.createElement("div");
    w.className = "table-wrap";
    t.before(w);
    w.append(t);
  }
  // —— 三区制视觉分层（模式命中才生效）：合同区/附录容器、合同块卡片、概念卡片 ——
  const wrapZoneFrom = (h2, cls) => {
    const section = document.createElement("section");
    section.className = cls;
    h2.before(section);
    let node = h2;
    while (node) {
      const next = node.nextElementSibling;
      section.append(node);
      node = next && next.tagName !== "H2" ? next : null;
    }
    return section;
  };
  const contractH2 = [...contentEl.querySelectorAll("h2")].find((h) => h.textContent.trim().startsWith("合同区"));
  if (contractH2) {
    const zone = wrapZoneFrom(contractH2, "zone-contract");
    const blkKind = (t) =>
      /术语/.test(t) ? "terms" : /API/i.test(t) ? "api" : /Data/i.test(t) ? "data" :
      /UI/i.test(t) ? "ui" : /Must/i.test(t) ? "must" : /Risk|风险/i.test(t) ? "risk" :
      /Checklist|清单/i.test(t) ? "check" : "misc";
    for (const h3 of [...zone.querySelectorAll("h3")]) {
      const card = document.createElement("div");
      card.className = "contract-block blk-" + blkKind(h3.textContent);
      h3.before(card);
      let node = h3;
      while (node) {
        const next = node.nextElementSibling;
        card.append(node);
        node = next && next.tagName !== "H3" ? next : null;
      }
    }
    for (const li of zone.querySelectorAll(".blk-must > ul > li")) li.classList.add("invariant");
  }
  const appendixH2 = [...contentEl.querySelectorAll("h2")].find((h) => /^附录/.test(h.textContent.trim()));
  if (appendixH2) wrapZoneFrom(appendixH2, "zone-appendix");
  const cnNum = "一二三四五六七八九十";
  for (const p of [...contentEl.querySelectorAll("p")]) {
    const strong = p.firstElementChild;
    if (!strong || strong.tagName !== "STRONG" || p.firstChild !== strong) continue;
    const cm = strong.textContent.match(/^([一二三四五六七八九十]{1,3})、(.+)/);
    if (!cm || !p.textContent.trim().slice(strong.textContent.length)) continue;
    const card = document.createElement("div");
    card.className = "concept-card";
    const num = document.createElement("div");
    num.className = "concept-num";
    num.textContent = cm[1].length === 1 ? String(cnNum.indexOf(cm[1]) + 1) : cm[1];
    const title = document.createElement("div");
    title.className = "concept-title";
    title.textContent = cm[2].replace(/。$$/, "");
    const bodyEl = document.createElement("div");
    bodyEl.className = "concept-body";
    strong.remove();
    while (p.firstChild) bodyEl.append(p.firstChild);
    card.append(num, title, bodyEl);
    p.replaceWith(card);
  }
  // —— 导读行："> 一句话：…" 引用块升格为醒目 takeaway 卡（模式命中才生效） ——
  for (const bq of contentEl.querySelectorAll("blockquote")) {
    const p0 = bq.querySelector("p");
    if (!p0 || !p0.textContent.trimStart().startsWith("一句话：")) continue;
    bq.classList.add("takeaway");
    const first = p0.firstChild;
    if (first && first.nodeType === 3) {
      first.textContent = first.textContent.replace(/^\s*一句话：\s*/, "");
      const label = document.createElement("span");
      label.className = "takeaway-label";
      label.textContent = "一句话";
      p0.prepend(label);
    }
  }
  // —— Task packet 族：机读投影的人读分层（判族命中才生效） ——
  if (DOC_META._kind === "task") {
    // 头部元数据段：Epic 行弱化（banner 已承载）；Generated from 折叠；Task scope 升格 callout
    for (const p of [...contentEl.querySelectorAll("p")]) {
      const first = p.firstElementChild;
      if (!first || first.tagName !== "STRONG" || p.firstChild !== first) continue;
      const label = first.textContent.trim();
      if (label.startsWith("Epic:")) {
        p.classList.add("task-meta-row");
      } else if (label.startsWith("Generated from:")) {
        // 相邻行会并入同一段：先把 "Task scope:" 起的节点拆出去
        const scopeStrong = [...p.querySelectorAll("strong")]
          .find((s) => s.textContent.trim().startsWith("Task scope:"));
        let scopeBox = null;
        if (scopeStrong) {
          scopeBox = document.createElement("div");
          scopeBox.className = "task-scope-callout";
          const nodes = [];
          let n = scopeStrong;
          while (n) { const nx = n.nextSibling; nodes.push(n); n = nx; }
          nodes.forEach((nd) => scopeBox.append(nd));
        }
        const det = document.createElement("details");
        det.className = "gen-from";
        const sum = document.createElement("summary");
        sum.textContent = "溯源锚点（Generated from）";
        const inner = document.createElement("p");
        while (p.firstChild) inner.append(p.firstChild);
        det.append(sum, inner);
        p.replaceWith(det);
        if (scopeBox) det.after(scopeBox);
      } else if (label.startsWith("Task scope:")) {
        const box = document.createElement("div");
        box.className = "task-scope-callout";
        while (p.firstChild) box.append(p.firstChild);
        p.replaceWith(box);
      }
    }
    // 执行合同字段升格语义卡片（复用合同块样式）：先看哪、能改哪、怎么执行、何时停、何时算完
    const cardKinds = [
      [/^Read first/, "data"],
      [/^Write scope/, "ui"],
      [/^Execution note/, "api"],
      [/^Stop conditions/, "risk"],
    ];
    for (const h3 of [...contentEl.querySelectorAll("h3")]) {
      const hit = cardKinds.find(([re]) => re.test(h3.textContent.trim()));
      if (!hit) continue;
      const card = document.createElement("div");
      card.className = "contract-block blk-" + hit[1];
      h3.before(card);
      let node = h3;
      while (node) {
        const next = node.nextElementSibling;
        card.append(node);
        node = next && !/^H[23]$$/.test(next.tagName) ? next : null;
      }
    }
    const dodH2 = [...contentEl.querySelectorAll("h2")]
      .find((h) => /Definition of Done/i.test(h.textContent));
    if (dodH2) {
      const card = document.createElement("div");
      card.className = "contract-block blk-check";
      dodH2.before(card);
      let node = dodH2;
      while (node) {
        const next = node.nextElementSibling;
        card.append(node);
        node = next && next.tagName !== "H2" ? next : null;
      }
    }
  }
  // —— EARS 增强（PRD 族）：R 编号+句式徽章、来源标签+统计/过滤、Epic 标题 ——
  const earsClass = { When: "when", If: "if", While: "while", Where: "where", Ubiquitous: "ubi", Scenario: "scenario" };
  for (const li of contentEl.querySelectorAll("li")) {
    const strong = li.querySelector("strong");
    if (!strong || !li.textContent.trimStart().startsWith(strong.textContent)) continue;
    const m = strong.textContent.match(/^(R\d+)\s*\((When|If|While|Where|Ubiquitous|Scenario)(?::\s*(.+))?\)/);
    if (!m) continue;
    li.classList.add("req");
    strong.textContent = m[1];
    const badge = document.createElement("span");
    badge.className = "ears-badge ears-" + earsClass[m[2]];
    badge.textContent = m[2] + (m[3] ? ": " + m[3] : "");
    strong.after(badge);
  }
  for (const li of contentEl.querySelectorAll("li.req")) {
    li.innerHTML = li.innerHTML.replaceAll("系统应", '<span class="subj">系统</span>应');
  }
  for (const ul of new Set([...contentEl.querySelectorAll("li.req")].map((li) => li.parentElement))) {
    [...ul.children].forEach((li, i) => { li.dataset.docIndex = i; });
  }
  const srcMap = { "[用户]": "user", "[调研]": "research", "[推断]": "inferred", "[未验证假设]": "assumption" };
  const srcCount = { user: 0, research: 0, inferred: 0, assumption: 0 };
  for (const code of contentEl.querySelectorAll("code")) {
    const kind = srcMap[code.textContent.trim()];
    if (!kind) continue;
    code.classList.add("src-chip", "src-" + kind);
    if (code.closest("blockquote")) continue;
    srcCount[kind] += 1;
    const req = code.closest("li.req");
    if (req && (kind === "inferred" || kind === "assumption")) req.classList.add("has-inferred");
  }
  const typeOrder = { ubi: 0, when: 1, while: 2, where: 3, scenario: 4, if: 5 };
  const typeName = { ubi: "Ubiquitous", when: "When", while: "While", where: "Where", scenario: "Scenario", if: "If" };
  const typeCount = { ubi: 0, when: 0, while: 0, where: 0, scenario: 0, if: 0 };
  const typeOf = (li) => {
    const b = li.querySelector(".ears-badge");
    for (const k in typeOrder) if (b && b.classList.contains("ears-" + k)) return k;
    return null;
  };
  for (const li of contentEl.querySelectorAll("li.req")) {
    const k = typeOf(li);
    if (k) typeCount[k] += 1;
  }
  const reqTotal = Object.values(typeCount).reduce((a, b) => a + b, 0);
  if (reqTotal > 0 || srcCount.inferred + srcCount.assumption > 0) {
    const bar = document.createElement("div");
    bar.className = "src-toolbar";
    if (srcCount.user + srcCount.research + srcCount.inferred + srcCount.assumption > 0) {
      const label = document.createElement("span");
      label.textContent = "来源标注：[用户] " + srcCount.user + " · [调研] " + srcCount.research +
        " · [推断] " + srcCount.inferred + " · [未验证假设] " + srcCount.assumption;
      const btn = document.createElement("button");
      btn.textContent = "只看待确认（推断/假设）";
      btn.addEventListener("click", () => {
        const on = document.body.classList.toggle("filter-inferred");
        btn.textContent = on ? "显示全部需求" : "只看待确认（推断/假设）";
      });
      bar.append(label, btn);
    }
    if (reqTotal > 0) {
      const tLabel = document.createElement("span");
      tLabel.textContent = "句式：" + Object.keys(typeOrder)
        .filter((k) => typeCount[k] > 0)
        .map((k) => typeName[k] + " " + typeCount[k]).join(" · ");
      let grouped = false;
      const gBtn = document.createElement("button");
      gBtn.textContent = "按句式分组";
      gBtn.addEventListener("click", () => {
        grouped = !grouped;
        for (const ul of new Set([...contentEl.querySelectorAll("li.req")].map((li) => li.parentElement))) {
          const items = [...ul.children].filter((c) => c.matches("li.req"));
          if (items.length < 2) continue;
          items.sort((a, b) => grouped
            ? ((typeOrder[typeOf(a)] ?? 9) - (typeOrder[typeOf(b)] ?? 9)) ||
              (Number(a.dataset.docIndex) - Number(b.dataset.docIndex))
            : Number(a.dataset.docIndex) - Number(b.dataset.docIndex));
          items.forEach((li) => ul.append(li));
        }
        gBtn.textContent = grouped ? "恢复文档顺序" : "按句式分组";
      });
      bar.append(tLabel, gBtn);
    }
    contentEl.prepend(bar);
  }
  for (const h3 of contentEl.querySelectorAll("h3")) {
    if (h3.textContent.startsWith("Epic ")) h3.classList.add("epic-head");
  }
  // —— Plan/Epic/Story 增强：ID 令牌芯片（D/ACD/T/U/Story），标题与代码块除外 ——
  const tokRe = /\b(ACD\d+|D\d(?!\d)|T\d{3}|U\d(?!\d))\b|\bStory\s(\d+\.\d+)\b/g;
  const tokClass = (t) =>
    t.startsWith("ACD") ? "tok-acd" : t.startsWith("Story") ? "tok-story" :
    t[0] === "D" ? "tok-d" : t[0] === "T" ? "tok-t" : "tok-u";
  const tokTest = new RegExp(tokRe.source); // 非全局副本：全局正则的 .test 有 lastIndex 状态坑
  const walker = document.createTreeWalker(contentEl, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const p = node.parentElement;
      if (!p || p.closest("pre, script, .mermaid, h1, h2, h3, h4, a, nav")) return NodeFilter.FILTER_REJECT;
      return tokTest.test(node.textContent) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
    },
  });
  const textNodes = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode);
  for (const node of textNodes) {
    const frag = document.createDocumentFragment();
    let last = 0;
    const text = node.textContent;
    for (const m of text.matchAll(tokRe)) {
      const tok = m[0];
      frag.append(text.slice(last, m.index));
      const span = document.createElement("span");
      span.className = "chip tok " + tokClass(tok);
      span.textContent = tok;
      frag.append(span);
      last = m.index + tok.length;
    }
    frag.append(text.slice(last));
    node.replaceWith(frag);
  }
  // —— 决策/同步状态与 Confidence 芯片（只作用于表格单元格） ——
  const stRe = /^(assumed|pending approval|pending|approved|synced)\b/i;
  for (const td of contentEl.querySelectorAll("td")) {
    const raw = td.textContent.trim();
    const sm = raw.match(stRe);
    if (sm && raw.length < 60) {
      const cls = "st-" + sm[1].toLowerCase().split(" ")[0];
      td.innerHTML = td.innerHTML.replace(sm[1], '<span class="chip ' + cls + '">' + sm[1] + "</span>");
    }
    if (/Confidence:\s*[HML]/.test(td.innerHTML)) {
      td.innerHTML = td.innerHTML.replace(/Confidence:\s*([HML])/g,
        (_, c) => 'Confidence: <span class="chip conf-' + c + '">' + c + "</span>");
    }
  }
  // —— 标题锚点 ID（github 风格 slug，让 .md 里的 [x](#锚) 文内跳转在 HTML 里也生效） ——
  const slugify = (s) => s.trim().toLowerCase()
    .replace(/[^\w\s一-鿿-]/g, "").replace(/\s+/g, "-");
  for (const h of contentEl.querySelectorAll("h1, h2, h3, h4")) {
    if (!h.id) h.id = slugify(h.textContent);
  }
  // —— 目录：≥1240px 常驻侧栏 + 阅读位置高亮；窄屏折叠不占首屏 ——
  const heads = contentEl.querySelectorAll("h2, h3");
  if (heads.length >= 5) {
    const toc = document.createElement("details");
    toc.className = "toc";
    const summaryEl = document.createElement("summary");
    summaryEl.textContent = "目录";
    const list = document.createElement("ul");
    const spyHeads = [];
    let lastZone = "narrative";
    heads.forEach((h, i) => {
      if (!h.id) h.id = "sec-" + i;
      const zone = h.closest(".zone-contract") ? "contract" : h.closest(".zone-appendix") ? "appendix" : "narrative";
      if (zone !== lastZone && zone !== "narrative") {
        const divider = document.createElement("li");
        divider.className = "toc-divider";
        divider.textContent = zone === "contract" ? "合同区" : "附录";
        list.append(divider);
      }
      lastZone = zone;
      if (zone !== "narrative" && h.tagName === "H2") return; // 分区起始 h2 由分隔行代表
      const item = document.createElement("li");
      if (h.tagName === "H3") item.style.marginLeft = "1em";
      const a = document.createElement("a");
      a.href = "#" + h.id;
      a.textContent = h.textContent;
      a.dataset.head = h.id;
      item.append(a);
      list.append(item);
      spyHeads.push(h);
    });
    toc.append(summaryEl, list);
    contentEl.prepend(toc);
    const wide = window.matchMedia("(min-width: 1240px)");
    const applyWide = () => { toc.open = wide.matches; };
    applyWide();
    wide.addEventListener("change", applyWide);
    const linkOf = {};
    for (const a of list.querySelectorAll("a")) linkOf[a.dataset.head] = a;
    let activeLink = null;
    const spy = new IntersectionObserver((entries) => {
      for (const e of entries) {
        if (!e.isIntersecting) continue;
        if (activeLink) activeLink.classList.remove("active");
        activeLink = linkOf[e.target.id] || null;
        if (activeLink) activeLink.classList.add("active");
      }
    }, { rootMargin: "0px 0px -70% 0px" });
    spyHeads.forEach((h) => spy.observe(h));
  }
  // —— mermaid：暖色主题与页面一致；库加载/渲染失败时降级成可折叠源码卡，不糊原文 ——
  const mermaidDivs = [...contentEl.querySelectorAll(".mermaid")];
  if (mermaidDivs.length) {
    const sources = mermaidDivs.map((d) => d.textContent);
    if (typeof mermaid !== "undefined") {
      const dark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      mermaid.initialize({
        startOnLoad: false,
        theme: "base",
        themeVariables: dark ? {
          background: "#2e2921", primaryColor: "#383226", primaryTextColor: "#d9d2c2",
          primaryBorderColor: "#5a5140", lineColor: "#9a917e", secondaryColor: "#32424c",
          tertiaryColor: "#332d24", clusterBkg: "#332d24", clusterBorder: "#463f30",
          edgeLabelBackground: "#2e2921", fontSize: "14px",
          fontFamily: '"PingFang SC", "Hiragino Sans GB", sans-serif',
        } : {
          background: "#fffdf6", primaryColor: "#efe9da", primaryTextColor: "#3a352b",
          primaryBorderColor: "#c9bfa4", lineColor: "#8a7f68", secondaryColor: "#e3ecf1",
          tertiaryColor: "#fbf8ef", clusterBkg: "#fbf8ef", clusterBorder: "#e4dcc9",
          edgeLabelBackground: "#fffdf6", fontSize: "14px",
          fontFamily: '"PingFang SC", "Hiragino Sans GB", sans-serif',
        },
      });
      try {
        await mermaid.run({ querySelector: ".mermaid" });
      } catch (e) {
        console.error("mermaid render failed:", e);
      }
    }
    mermaidDivs.forEach((div, i) => {
      if (div.querySelector("svg") && !div.querySelector('svg[aria-roledescription="error"]')) return;
      const box = document.createElement("div");
      box.className = "mermaid-fallback";
      const note = document.createElement("div");
      note.textContent = "⚠ 图表未能渲染（图表库需网络加载，或图源有语法问题）——图的文字源码：";
      const det = document.createElement("details");
      const detSum = document.createElement("summary");
      detSum.textContent = "展开查看";
      const pre = document.createElement("pre");
      pre.textContent = sources[i];
      det.append(detSum, pre);
      box.append(note, det);
      div.replaceWith(box);
    });
  }
});
</script>
</body>
</html>
""")

DOC_KIND_LABEL = {
    "epic-review-pack-readme": "Review Pack · 入口",
    "epic-technical-design": "Review Pack · 技术设计",
    "epic-decisions": "Review Pack · 决策真相源",
    "epic": "Epic",
    "story": "Story",
    "prd": "PRD",
    "task": "Task Packet · 执行投影",
    "task-index": "Task Index · 执行入口",
}


def split_frontmatter(text: str) -> tuple[str, str]:
    """返回 (frontmatter 原文不含围栏, 正文)。无 frontmatter 时前者为空串。"""
    if not text.startswith("---\n") and not text.startswith("---\r\n"):
        return "", text
    lines = text.splitlines(keepends=True)
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "".join(lines[1:i]), "".join(lines[i + 1 :])
    return "", text


def parse_meta(frontmatter: str, body: str, md_path: Path) -> dict:
    """从 frontmatter + 内容特征提取文档头横幅用的元信息。"""
    meta: dict[str, str] = {}
    for line in frontmatter.splitlines():
        m = re.match(r"^([A-Za-z_]+):\s*[\"']?([^\"']+?)[\"']?\s*$", line)
        if m:
            meta[m.group(1)] = m.group(2)
    kind = meta.get("type", "")
    if not kind:
        if md_path.name == "task-index.md":
            kind = "task-index"
        elif re.match(r"^T\d{3}(-|\.md$)", md_path.name):
            kind = "task"
        elif meta.get("epic_id") and meta.get("epic_name"):
            kind = "epic"
        elif re.match(r"^us\d{3}-", md_path.name) or re.search(r"^### Story \d+\.\d+", body, re.M):
            kind = "story"
        elif "EARS" in body[:2000]:
            kind = "prd"
    meta["_kind"] = kind
    meta["_kind_label"] = DOC_KIND_LABEL.get(kind, "")
    # task 族：从模板固定格式的正文提取 banner 芯片素材（旧版 task 文档缺字段则跳过，不报错）
    if kind == "task":
        def grab_inline(label: str) -> str:
            m = re.search(rf"\*\*{label}:\*\*\s*([^·\n]+)", body)
            return m.group(1).strip() if m else ""
        m = re.search(r"\*\*Epic:\*\*\s*\[([^\]]+)\]", body)
        meta["_epic_name"] = m.group(1).strip() if m else ""
        meta["_task_scope"] = grab_inline("Unit / Scope")
        meta["_wave"] = grab_inline("Wave")
        meta["_depends"] = grab_inline("Depends")
        for fld, key in (("Test policy", "_test_policy"), ("Risk class", "_risk"),
                         ("UI class", "_ui_class")):
            m = re.search(rf"^-\s*{fld}:\s*([^\n（(]+)", body, re.M)
            if m and "{" not in m.group(1):
                meta[key] = m.group(1).strip()
    elif kind == "task-index":
        m = re.search(r"\*\*Execution policy:\*\*\s*(fast|strict)", body)
        if m and not meta.get("execution_policy"):
            meta["execution_policy"] = m.group(1)
    return meta


def build_banner(meta: dict, title: str) -> str:
    """plan/epic/story 族生成文档头横幅；识别不出家族时返回空串（零影响）。"""
    if not meta.get("_kind_label"):
        return ""
    chips: list[str] = []
    if meta.get("epic_id"):
        chips.append(f'<span class="chip meta">Epic {html.escape(meta["epic_id"])}</span>')
    policy = meta.get("execution_policy", "")
    if policy:
        cls = "pol-strict" if "strict" in policy else "pol-fast"
        chips.append(f'<span class="chip {cls}">{html.escape(policy)}</span>')
    if meta.get("status"):
        chips.append(f'<span class="chip doc-status">{html.escape(meta["status"])}</span>')
    if meta.get("priority"):
        chips.append(f'<span class="chip meta">{html.escape(meta["priority"])}</span>')
    if meta.get("date"):
        chips.append(f'<span class="chip meta">{html.escape(meta["date"])}</span>')
    # task 族芯片（字段缺失即跳过，兼容旧版 task 文档）
    if meta.get("_epic_name"):
        chips.append(f'<span class="chip meta">{html.escape(meta["_epic_name"])}</span>')
    if meta.get("_wave"):
        chips.append(f'<span class="chip meta">Wave {html.escape(meta["_wave"])}</span>')
    if meta.get("_depends"):
        chips.append(f'<span class="chip meta">Depends: {html.escape(meta["_depends"])}</span>')
    risk = meta.get("_risk", "")
    if risk:
        cls = "pol-strict" if "strict" in risk else "pol-fast"
        chips.append(f'<span class="chip {cls}">risk: {html.escape(risk)}</span>')
    if meta.get("_ui_class"):
        chips.append(f'<span class="chip doc-status">UI: {html.escape(meta["_ui_class"])}</span>')
    if meta.get("_test_policy"):
        chips.append(f'<span class="chip meta">{html.escape(meta["_test_policy"])}</span>')
    scope_line = (
        f'<div class="scope-line">{html.escape(meta["_task_scope"])}</div>'
        if meta.get("_task_scope") else ""
    )
    meta_row = f'<div class="meta-row">{"".join(chips)}</div>' if chips else ""
    return (
        '<header class="doc-banner">'
        f'<div class="kicker">{html.escape(meta["_kind_label"])}</div>'
        f'<div style="font-size:1.05rem;font-weight:600">{html.escape(title)}</div>'
        f"{scope_line}{meta_row}</header>"
    )


def extract_title(body: str, fallback: str) -> str:
    """取正文第一个 H1 作为页面标题；跳过 code fence 内的 '# ' 行。"""
    in_fence = False
    for line in body.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence and line.startswith("# "):
            return line[2:].strip()
    return fallback


def journey_source_digest(body: str) -> str | None:
    """`## 用户旅程` 章节的内容摘要——archify 旅程图过期检查的比对基准。"""
    m = re.search(r"^## 用户旅程\n.*?(?=^## |\Z)", body, re.S | re.M)
    return hashlib.sha1(m.group(0).encode("utf-8")).hexdigest()[:16] if m else None


def journey_embed(md_path: Path, body: str) -> dict | None:
    """同目录存在 archify 旅程图（journey.html）时返回 iframe 引用信息。

    这是"手工精装修图必须与旅程章节同步"规则的兜底检查：sidecar 文件
    journey.source-digest 记录生成图时的章节摘要（archify schema 不允许 meta 扩展字段，
    故独立存放），与当前摘要不一致 → 页面警示横幅 + 构建期 stderr warning。
    """
    html_path = md_path.parent / "journey.html"
    if not html_path.is_file():
        return None
    digest = journey_source_digest(body)
    if digest is None:
        return None
    sidecar = md_path.parent / "journey.source-digest"
    try:
        recorded = sidecar.read_text(encoding="utf-8").strip()
    except OSError:
        recorded = ""
    stale = recorded != digest
    if stale:
        print(
            f"warning: {html_path.name} 可能过期——旅程章节摘要 {digest} ≠ "
            f"journey.source-digest 记录值 {recorded or '(缺失)'}；"
            f"请基于 journey.workflow.json 用 archify 重新生成，"
            f"并把新摘要写入 {sidecar.name}",
            file=sys.stderr,
        )
    return {"src": html_path.name, "stale": stale}


def render_file(md_path: Path) -> Path:
    text = md_path.read_text(encoding="utf-8")
    frontmatter, body = split_frontmatter(text)
    meta = parse_meta(frontmatter, body, md_path)  # 在 fix_cjk_strong 之前：**…** 正则要吃原文
    embed = journey_embed(md_path, body)  # 摘要基准取原文，须在 fix_cjk_strong 之前
    body = fix_cjk_strong(body)
    title = extract_title(body, md_path.stem)

    frontmatter_block = ""
    if frontmatter.strip():
        frontmatter_block = (
            '<details class="frontmatter"><summary>文档元数据（frontmatter）</summary>'
            f"<pre>{html.escape(frontmatter.strip())}</pre></details>"
        )

    # < 转义防正文中的 </script> / <!-- 破坏内联 script；U+2028/2029 是旧 JS 引擎的行终止符
    def js_json(value) -> str:
        return (
            json.dumps(value, ensure_ascii=False)
            .replace("<", "\\u003c")
            .replace("\u2028", "\\u2028")
            .replace("\u2029", "\\u2029")
        )

    out_path = md_path.with_suffix(".html")
    out_path.write_text(
        PAGE_TEMPLATE.substitute(
            title=html.escape(title),
            source_name=html.escape(md_path.name),
            banner_block=build_banner(meta, title),
            frontmatter_block=frontmatter_block,
            marked_script_tag=marked_script_tag(),
            mermaid_script_tag=MERMAID_SCRIPT_TAG if "```mermaid" in body else "",
            md_json=js_json(body),
            doc_meta_json=js_json(meta),
            journey_embed_json=js_json(embed),
        ),
        encoding="utf-8",
    )
    return out_path


def collect_md_files(args: list[str]) -> list[Path]:
    files: list[Path] = []
    for arg in args:
        p = Path(arg)
        if p.is_dir():
            files.extend(sorted(p.rglob("*.md")))
        elif p.is_file() and p.suffix == ".md":
            files.append(p)
        else:
            print(f"error: 不是 .md 文件或目录: {arg}", file=sys.stderr)
            sys.exit(1)
    return files


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    files = collect_md_files(sys.argv[1:])
    if not files:
        print("error: 未找到任何 .md 文件", file=sys.stderr)
        sys.exit(1)
    failed: list[str] = []
    for md_path in files:
        try:
            out = render_file(md_path)
        except Exception as exc:  # 单文件失败不中断批量
            failed.append(str(md_path))
            print(f"failed: {md_path} ({exc})", file=sys.stderr)
            continue
        print(f"rendered: {out}")
    if failed:
        print(f"error: {len(failed)} 个文件渲染失败: {', '.join(failed)}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
